import { Pokemon } from './pokemon';
export const dataPokemons = [
  new Pokemon(1,['Overgrow'],15.2,['Fire','Flying','Ice','Psychic'], 1, 28,'Bulbasaur',['grass', 'poison']),
  new Pokemon(2,['Overgrow'],28.7,['Fire','Flying','Ice','Psychic'], 2, 39,'Ivysaur',['grass', 'poison']),
  new Pokemon(3,['Thick Fat'],342.8,['Fire','Flying','Ice','Psychic'], 3, 94,'Venusaur',['grass', 'poison']),
  new Pokemon(4,['Blaze'],18.7,['Ground','Rock','Water'], 4, 24,'Charmander',['fire']),
  new Pokemon(5,['Blaze'], 41.9,['Ground','Rock','Water'], 5, 43,'Charmeleon',['fire']),
  new Pokemon(6,['Blaze'],9999,['Water','Electric','Rock'], 6, 1102,'Charizard',['fire', 'flying']),
  new Pokemon(7,['Torrent'],19.8,['Electric','Grass'], 7, 20,'Squirtle',['water']),
  new Pokemon(8,['Torrent'],49.6,['Electric','Grass'], 8, 39,'Wartortle',['water']),
  new Pokemon(9,['Mega Launcher'],222.9,['Electric','Grass'], 9, 63,'Blastoise',['water']),
  new Pokemon(10,['Shield Dust'],6.4,['Fire','Flying','Rock'], 10, 12,'Caterpie',['bug']),
  new Pokemon(11,['Shed Skin'],21.8,['Fire','Flying','Rock'], 11, 28,'Metapod',['bug']),
  new Pokemon(12,['Compound Eyes'],9999,['Fire','Flying','Electric','Ice','Rock'], 12, 669,'Butterfree',['bug', 'flying']),
  new Pokemon(13,['Shield Dust'], 7.1,['Fire','Flying','Psychic','Rock'], 13, 12,'Weedle',['bug', 'poison']),
  new Pokemon(14,['Shed Skin'],22,['Fire','Flying','Psychic','Rock'], 14, 24,'Kakuna',['bug', 'poison']),
  new Pokemon(15,['Adaptability'],89.3,['Fire','Flying','Psychic','Rock'], 15, 55,'Beedrill',['bug', 'poison']),
  new Pokemon(16,['Keen Eye','Tangled Feet'],4,['Electric','Ice','Rock'], 16, 12,'Pidgey',['flying']),
  new Pokemon(17,['Keen Eye','Tangled Feet'],66.1,['Electric','Ice','Rock'], 17, 43,'Pidgeotto',['flying']),
  new Pokemon(18,['No Guard'],111.3,['Electric','Ice','Rock'], 18, 87,'Pidgeot',['flying']),
  new Pokemon(19,['Gluttony','Hustle'], 8.4,['Fairy','Bug','Fighting'], 19, 12,'Rattata',['dark', 'normal']),
  new Pokemon(20,['Gluttony','Hustle'],56.2,['Fairy','Bug','Fighting'], 20, 28,'Raticate',['dark', 'normal']),
  new Pokemon(21,['Keen Eye'],4.4,['Electric','Ice','Rock'], 21, 12,'Spearow',['normal', 'flying']),
  new Pokemon(22,['Keen Eye'],83.8,['Electric','Ice','Rock'], 22, 47,'Fearow',['normal', 'flying']),
  new Pokemon(23,['Intimidate','Shed Skin'],15.2,['Ground','Psychic'], 23, 79,'Ekans',['poison']),
  new Pokemon(24,['Intimidate','Shed Skin'],143.3,['Ground','Psychic'], 24, 138,'Arbok',['poison']),
  new Pokemon(25,['Overgrow'],9999,['Ground'], 25, 827,'Pikachu',['electric']),
  new Pokemon(26,['Overgrow'],46.3,['Ghost','Dark','Bug','Ground'], 26, 28,'Raichu',['electric', 'psychic']),

]
